from enum import Flag

class TestCaseType(Flag):
    NONE = 0
    SKIP = 1
    DEV = 2  # instead of running the test and comparing the results, run all imported solvers with the input to find out the results
    FOCUS = 4  # to be able to mark test(s) selectively and run only it/them
    BASE = 8  # manually crafted tests focusing on some feature
    FULL = 16  # full boards as gotten from the game
    PERF = 32  # performance tests, usually tests containing lots of gems leading to lots of possibilities, thus longer running times
    ALL = DEV | FOCUS | BASE | FULL | PERF

tests_suite = [
  {
    "name": "empty board",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [0, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 0,
    "potential_progress": 0,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L1 bottom",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [1, 0, 0, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [0, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 0,
    "potential_progress": 1,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L1 top",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [1, 0, 0, 0],
    "free": [0, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 0,
    "potential_progress": 1,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L1 free",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [1, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 0,
    "potential_progress": 0,
    "unlocked_part": 0,
    "unlocked_empty": 1
  },
  {
    "name": "one L1 bot merge",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [1, 0, 0, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [1, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 1,
    "potential_progress": 1,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "one L1 top merge",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [1, 0, 0, 0],
    "free": [1, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 1,
    "potential_progress": 1,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "two L1 free",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [2, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 0,
    "potential_progress": 0,
    "unlocked_part": 0,
    "unlocked_empty": 2
  },
  {
    "name": "one L1 bot L2 top merge",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [1, 0, 0, 0],
    "locked_top": [0, 1, 0, 0],
    "free": [1, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 1,
    "max_keys": 3,
    "progress": 2,
    "potential_progress": 2,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L1 top L2 bot merge",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 1, 0, 0],
    "locked_top": [1, 0, 0, 0],
    "free": [1, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 1,
    "max_keys": 3,
    "progress": 2,
    "potential_progress": 2,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L2 bot L3 top merge",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 1, 0, 0],
    "locked_top": [0, 0, 1, 0],
    "free": [0, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 2,
    "potential_progress": 2,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L2 top L3 bot merge",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 1, 0],
    "locked_top": [0, 1, 0, 0],
    "free": [0, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 2,
    "potential_progress": 2,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L3 bot L4 top merge",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 1, 0],
    "locked_top": [0, 0, 0, 1],
    "free": [0, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 3,
    "potential_progress": 3,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L3 top L4 bot merge",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 1],
    "locked_top": [0, 0, 1, 0],
    "free": [0, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 3,
    "potential_progress": 3,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L4 top L4 bot merge",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 1],
    "locked_top": [0, 0, 0, 1],
    "free": [0, 0, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "two L1 top L2 bot merges into L4",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [2, 0, 0, 0],
    "locked_top": [0, 2, 0, 0],
    "free": [2, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 6,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "two L1 bot L2 top merges into L4",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 2, 0, 0],
    "locked_top": [2, 0, 0, 0],
    "free": [2, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 6,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "one L1 top ignores free L2",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [1, 0, 0, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [1, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 1,
    "potential_progress": 1,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "one L1 bot ignores free L2",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [1, 0, 0, 0],
    "free": [1, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 1,
    "potential_progress": 1,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "one L2 top ignores free L3",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 1, 0, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [0, 1, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 1,
    "potential_progress": 1,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "one L2 bot ignores free L3",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 1, 0, 0],
    "free": [0, 1, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 1,
    "potential_progress": 1,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "one L3 top ignores free L4",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 1, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [0, 0, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 1,
    "potential_progress": 1,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "one L3 bot ignores free L4",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 1, 0],
    "free": [0, 0, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 1,
    "potential_progress": 1,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "gobble locked L4 bot with free",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 1],
    "locked_top": [0, 0, 0, 0],
    "free": [0, 0, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 2,
    "potential_progress": 2,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 top with free",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 0, 1],
    "free": [0, 0, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 2,
    "potential_progress": 2,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 bots with free",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 2],
    "locked_top": [0, 0, 0, 0],
    "free": [0, 0, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 tops with free",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 0, 2],
    "free": [0, 0, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 bot with bot",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 1, 1],
    "locked_top": [0, 0, 0, 0],
    "free": [0, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 3,
    "potential_progress": 3,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 top with top",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 1, 1],
    "free": [0, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 3,
    "potential_progress": 3,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 bots with bot",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 1, 2],
    "locked_top": [0, 0, 0, 0],
    "free": [0, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 5,
    "potential_progress": 5,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 tops with top",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 1, 2],
    "free": [0, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 5,
    "potential_progress": 5,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 bot with full",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 1, 0, 1],
    "locked_top": [0, 0, 1, 0],
    "free": [0, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 top with full",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 1, 0],
    "locked_top": [0, 1, 0, 1],
    "free": [0, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 bots with full",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 1, 0, 2],
    "locked_top": [0, 0, 1, 0],
    "free": [0, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 6,
    "potential_progress": 6,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "gobble locked L4 tops with full",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 1, 0],
    "locked_top": [0, 1, 0, 2],
    "free": [0, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 6,
    "potential_progress": 6,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "leave free L4 unmerged",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [0, 0, 0, 2],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 0,
    "potential_progress": 0,
    "unlocked_part": 0,
    "unlocked_empty": 2
  },
  {
    "name": "leave free L4 unmerged in presence of merged key",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 1],
    "locked_top": [0, 0, 0, 1],
    "free": [0, 0, 0, 3],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 0,
    "unlocked_empty": 2
  },
  {
    "name": "leave free L1-4 unmerged",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [0, 0, 0, 0],
    "free": [2, 2, 2, 2],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 0,
    "potential_progress": 0,
    "unlocked_part": 0,
    "unlocked_empty": 8
  },
  {
    "name": "leave free L1-4 unmerged in presence of merged key",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 1],
    "locked_top": [0, 0, 0, 1],
    "free": [2, 2, 2, 3],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 0,
    "unlocked_empty": 8
  },
  {
    "name": "leave free L1-2, merge free L3 for L4 key",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 1],
    "locked_top": [0, 0, 0, 1],
    "free": [2, 2, 4, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 4,
    "potential_progress": 4,
    "unlocked_part": 0,
    "unlocked_empty": 6
  },
  {
    "name": "leave free L2 bot unmerged, merge free L2 for L4 key",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [2, 0, 0, 1],
    "locked_top": [0, 0, 0, 1],
    "free": [2, 2, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 6,
    "potential_progress": 6,
    "unlocked_part": 2,
    "unlocked_empty": 0
  },
  {
    "name": "leave free L2 top unmerged, merge free L2 for L4 key",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 1],
    "locked_top": [2, 0, 0, 1],
    "free": [2, 2, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 6,
    "potential_progress": 6,
    "unlocked_part": 2,
    "unlocked_empty": 0
  },
  {
    "name": "unmerged top is better than unmerged empty",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 1],
    "locked_top": [1, 0, 0, 1],
    "free": [1, 2, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 5,
    "potential_progress": 5,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "unmerged bot is better than unmerged empty",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [1, 0, 0, 1],
    "locked_top": [0, 0, 0, 1],
    "free": [1, 2, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 5,
    "potential_progress": 5,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "one unmerged top is better than two unmerged empties",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [0, 0, 0, 1],
    "locked_top": [1, 0, 0, 1],
    "free": [3, 1, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 5,
    "potential_progress": 5,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "one unmerged bot is better than two unmerged empties",
    "tctype": TestCaseType.BASE,
    "locked_bottom": [1, 0, 0, 1],
    "locked_top": [0, 0, 0, 1],
    "free": [3, 1, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 5,
    "potential_progress": 5,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "comment-6153598555 by Centaurus",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [3, 3, 0, 2],
    "locked_top": [4, 3, 1, 1],
    "free": [1, 2, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 10,
    "max_keys": 24,
    "progress": 11,
    "potential_progress": 20,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "comment-6152735906 by Stella Yolanda Zonker",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 1, 0, 0],
    "locked_top": [2, 2, 1, 1],
    "free": [0, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 9,
    "progress": 3,
    "potential_progress": 10,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "comment-6151362161 by szevasz",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 0, 1, 0],
    "locked_top": [1, 0, 2, 1],
    "free": [2, 2, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 4,
    "potential_progress": 6,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "comment-6149964806 by Muche",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [1, 1, 1, 2],
    "locked_top": [2, 5, 1, 1],
    "free": [4, 0, 3, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 15,
    "max_keys": 15,
    "progress": 14,
    "potential_progress": 17,
    "unlocked_part": 0,
    "unlocked_empty": 1
  },
  {
    "name": "comment-6149249510 by Muche",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [3, 1, 0, 1],
    "locked_top": [4, 0, 0, 0],
    "free": [3, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 4,
    "max_keys": 12,
    "progress": 6,
    "potential_progress": 10,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "comment-6148461376 by Stella Yolanda Zonker",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 2, 0, 1],
    "locked_top": [0, 0, 2, 0],
    "free": [1, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 6,
    "progress": 5,
    "potential_progress": 7,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "comment-6148124724 by Max Barbarian",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 2, 1, 3],
    "locked_top": [0, 1, 2, 0],
    "free": [0, 1, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 9,
    "progress": 9,
    "potential_progress": 13,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "comment-6147057517 by Rigel Blue",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [4, 0, 1, 2],
    "locked_top": [2, 1, 2, 1],
    "free": [2, 6, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 12,
    "max_keys": 18,
    "progress": 12,
    "potential_progress": 16,
    "unlocked_part": 1,
    "unlocked_empty": 4
  },
  {
    "name": "comment-6153869993 by Stella Yolanda Zonker",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 2, 2, 1],
    "locked_top": [3, 1, 1, 0],
    "free": [4, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 15,
    "progress": 11,
    "potential_progress": 11,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "comment-6155079334 by MarkusS",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 0, 0, 2],
    "locked_top": [1, 3, 2, 0],
    "free": [4, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 7,
    "max_keys": 9,
    "progress": 11,
    "potential_progress": 11,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc1",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 3, 1, 3],
    "locked_top": [1, 0, 0, 0],
    "free": [1, 0, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 9,
    "potential_progress": 11,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "tc2",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 0, 2, 3],
    "locked_top": [1, 0, 1, 0],
    "free": [4, 0, 2, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 6,
    "progress": 12,
    "potential_progress": 12,
    "unlocked_part": 3,
    "unlocked_empty": 1
  },
  {
    "name": "tc3",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 0, 0, 2],
    "locked_top": [0, 0, 1, 1],
    "free": [4, 0, 0, 2],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 6,
    "progress": 9,
    "potential_progress": 9,
    "unlocked_part": 2,
    "unlocked_empty": 0
  },
  {
    "name": "tc4",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 1, 0, 0],
    "locked_top": [0, 3, 1, 1],
    "free": [3, 1, 1, 2],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 5,
    "potential_progress": 7,
    "unlocked_part": 2,
    "unlocked_empty": 3
  },
  {
    "name": "tc5",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 1, 0, 0],
    "locked_top": [3, 3, 3, 2],
    "free": [1, 3, 2, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 12,
    "potential_progress": 14,
    "unlocked_part": 5,
    "unlocked_empty": 0
  },
  {
    "name": "tc6",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 1, 1, 0],
    "locked_top": [5, 0, 0, 0],
    "free": [4, 2, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 12,
    "progress": 6,
    "potential_progress": 9,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc7",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 3, 0, 0],
    "locked_top": [0, 3, 0, 0],
    "free": [2, 1, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 9,
    "progress": 2,
    "potential_progress": 6,
    "unlocked_part": 0,
    "unlocked_empty": 2
  },
  {
    "name": "tc8 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [3, 4, 4, 1],
    "locked_top": [1, 3, 0, 1],
    "free": [4, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 13,
    "max_keys": 15,
    "progress": 17,
    "potential_progress": 19,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc9",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 1, 0, 1],
    "locked_top": [1, 0, 0, 2],
    "free": [1, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 1,
    "max_keys": 6,
    "progress": 2,
    "potential_progress": 8,
    "unlocked_part": 0,
    "unlocked_empty": 1
  },
  {
    "name": "tc10 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [2, 2, 4, 1],
    "locked_top": [1, 0, 2, 1],
    "free": [9, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 12,
    "max_keys": 12,
    "progress": 14,
    "potential_progress": 15,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc11",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [3, 2, 2, 1],
    "locked_top": [5, 1, 0, 0],
    "free": [3, 0, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 18,
    "progress": 10,
    "potential_progress": 15,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc12 displayorder",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 0, 0, 2],
    "locked_top": [1, 3, 0, 1],
    "free": [0, 2, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 9,
    "progress": 8,
    "potential_progress": 11,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc13 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [1, 1, 1, 0],
    "locked_top": [1, 1, 1, 3],
    "free": [5, 1, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 9,
    "progress": 12,
    "potential_progress": 12,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "tc14 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [2, 3, 1, 0],
    "locked_top": [2, 0, 1, 2],
    "free": [2, 3, 2, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 12,
    "max_keys": 15,
    "progress": 11,
    "potential_progress": 13,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc15",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [3, 1, 2, 0],
    "locked_top": [3, 2, 0, 1],
    "free": [1, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 18,
    "progress": 7,
    "potential_progress": 13,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc16",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 1, 0, 2],
    "locked_top": [1, 2, 1, 0],
    "free": [1, 0, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 4,
    "max_keys": 12,
    "progress": 7,
    "potential_progress": 10,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc17",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 0, 2, 2],
    "locked_top": [0, 2, 2, 1],
    "free": [3, 1, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 15,
    "progress": 11,
    "potential_progress": 13,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc18",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [3, 1, 1, 0],
    "locked_top": [2, 3, 0, 1],
    "free": [2, 2, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 15,
    "progress": 9,
    "potential_progress": 12,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc19",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 3, 0, 3],
    "locked_top": [0, 0, 2, 1],
    "free": [3, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 9,
    "progress": 13,
    "potential_progress": 14,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc20",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [4, 0, 1, 3],
    "locked_top": [3, 0, 0, 0],
    "free": [2, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 9,
    "progress": 9,
    "potential_progress": 14,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc21",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [3, 0, 1, 2],
    "locked_top": [0, 3, 0, 0],
    "free": [5, 0, 3, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 9,
    "progress": 11,
    "potential_progress": 11,
    "unlocked_part": 0,
    "unlocked_empty": 3
  },
  {
    "name": "tc22",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 3, 0, 0],
    "locked_top": [1, 1, 2, 3],
    "free": [3, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 12,
    "progress": 12,
    "potential_progress": 14,
    "unlocked_part": 0,
    "unlocked_empty": 1
  },
  {
    "name": "tc23",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [3, 2, 3, 0],
    "locked_top": [1, 2, 0, 1],
    "free": [3, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 12,
    "progress": 11,
    "potential_progress": 13,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc24 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [2, 2, 3, 2],
    "locked_top": [2, 4, 2, 0],
    "free": [5, 3, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 18,
    "max_keys": 24,
    "progress": 19,
    "potential_progress": 19,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "tc25 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [1, 1, 2, 4],
    "locked_top": [2, 2, 0, 2],
    "free": [3, 1, 4, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 13,
    "max_keys": 18,
    "progress": 20,
    "potential_progress": 20,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc26 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [1, 3, 2, 1],
    "locked_top": [2, 2, 2, 1],
    "free": [7, 0, 4, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 19,
    "max_keys": 21,
    "progress": 16,
    "potential_progress": 16,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc27 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [0, 1, 2, 2],
    "locked_top": [3, 3, 1, 1],
    "free": [3, 1, 4, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 15,
    "max_keys": 15,
    "progress": 16,
    "potential_progress": 16,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc28",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 1, 3, 0],
    "locked_top": [1, 0, 0, 2],
    "free": [4, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 9,
    "progress": 8,
    "potential_progress": 9,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "tc29",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 2, 2, 2],
    "locked_top": [3, 1, 0, 1],
    "free": [2, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 7,
    "max_keys": 15,
    "progress": 13,
    "potential_progress": 15,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc30",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 0, 2, 1],
    "locked_top": [2, 1, 1, 2],
    "free": [4, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 15,
    "progress": 14,
    "potential_progress": 14,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc31",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [3, 1, 3, 1],
    "locked_top": [2, 1, 0, 1],
    "free": [6, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 10,
    "max_keys": 12,
    "progress": 14,
    "potential_progress": 14,
    "unlocked_part": 0,
    "unlocked_empty": 1
  },
  {
    "name": "tc32",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 1, 1, 0],
    "locked_top": [3, 1, 1, 1],
    "free": [4, 0, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 7,
    "max_keys": 9,
    "progress": 10,
    "potential_progress": 10,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc33",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 2, 2, 1],
    "locked_top": [3, 2, 0, 0],
    "free": [4, 2, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 10,
    "max_keys": 15,
    "progress": 11,
    "potential_progress": 11,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "tc34",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 2, 0, 1],
    "locked_top": [1, 4, 3, 0],
    "free": [4, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 10,
    "max_keys": 12,
    "progress": 11,
    "potential_progress": 13,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc35",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 0, 2, 3],
    "locked_top": [1, 1, 0, 1],
    "free": [1, 1, 2, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 9,
    "progress": 12,
    "potential_progress": 14,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "tc36",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 0, 1, 0],
    "locked_top": [1, 2, 1, 3],
    "free": [1, 0, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 6,
    "progress": 9,
    "potential_progress": 12,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc37 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [1, 2, 5, 3],
    "locked_top": [1, 2, 4, 0],
    "free": [3, 2, 2, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 18,
    "max_keys": 21,
    "progress": 18,
    "potential_progress": 21,
    "unlocked_part": 1,
    "unlocked_empty": 1
  },
  {
    "name": "tc38",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 1, 1, 0],
    "locked_top": [1, 1, 0, 0],
    "free": [2, 3, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 6,
    "progress": 5,
    "potential_progress": 5,
    "unlocked_part": 1,
    "unlocked_empty": 2
  },
  {
    "name": "tc39",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 0, 0, 0],
    "locked_top": [3, 0, 0, 1],
    "free": [1, 1, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 0,
    "max_keys": 0,
    "progress": 3,
    "potential_progress": 5,
    "unlocked_part": 2,
    "unlocked_empty": 2
  },
  {
    "name": "tc40",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 2, 0, 1],
    "locked_top": [4, 3, 5, 0],
    "free": [2, 2, 4, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 9,
    "progress": 13,
    "potential_progress": 16,
    "unlocked_part": 4,
    "unlocked_empty": 2
  },
  {
    "name": "tc41",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 3, 1, 2],
    "locked_top": [2, 2, 1, 1],
    "free": [3, 0, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 7,
    "max_keys": 18,
    "progress": 14,
    "potential_progress": 16,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc42",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [3, 0, 5, 0],
    "locked_top": [2, 2, 2, 0],
    "free": [0, 2, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 18,
    "progress": 4,
    "potential_progress": 14,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc43 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [2, 1, 1, 2],
    "locked_top": [1, 1, 1, 1],
    "free": [4, 3, 2, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 12,
    "max_keys": 12,
    "progress": 13,
    "potential_progress": 13,
    "unlocked_part": 0,
    "unlocked_empty": 1
  },
  {
    "name": "tc44",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 1, 0, 0],
    "locked_top": [4, 2, 0, 0],
    "free": [2, 1, 2, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 6,
    "progress": 5,
    "potential_progress": 8,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc45",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 0, 0, 2],
    "locked_top": [1, 0, 0, 0],
    "free": [3, 0, 2, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 3,
    "max_keys": 3,
    "progress": 5,
    "potential_progress": 5,
    "unlocked_part": 0,
    "unlocked_empty": 1
  },
  {
    "name": "tc46",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 1, 1, 0],
    "locked_top": [0, 3, 0, 0],
    "free": [4, 2, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 9,
    "progress": 7,
    "potential_progress": 7,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc47 perf",
    "tctype": TestCaseType.FULL | TestCaseType.PERF,
    "locked_bottom": [1, 6, 2, 4],
    "locked_top": [1, 2, 3, 3],
    "free": [6, 6, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 21,
    "max_keys": 27,
    "progress": 29,
    "potential_progress": 29,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc48",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 0, 1, 0],
    "locked_top": [1, 0, 1, 1],
    "free": [4, 2, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 6,
    "max_keys": 9,
    "progress": 7,
    "potential_progress": 7,
    "unlocked_part": 2,
    "unlocked_empty": 1
  },
  {
    "name": "tc49",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [4, 2, 5, 1],
    "locked_top": [1, 1, 1, 1],
    "free": [1, 2, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 12,
    "progress": 11,
    "potential_progress": 18,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc50",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 2, 0, 0],
    "locked_top": [2, 1, 2, 2],
    "free": [5, 1, 0, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 9,
    "progress": 12,
    "potential_progress": 12,
    "unlocked_part": 0,
    "unlocked_empty": 0
  },
  {
    "name": "tc51",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [3, 2, 0, 1],
    "locked_top": [1, 1, 1, 2],
    "free": [4, 0, 0, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 15,
    "progress": 14,
    "potential_progress": 14,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc52",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 3, 1, 0],
    "locked_top": [4, 0, 1, 0],
    "free": [2, 1, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 9,
    "max_keys": 15,
    "progress": 7,
    "potential_progress": 10,
    "unlocked_part": 0,
    "unlocked_empty": 1
  },
  {
    "name": "tc53",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [0, 0, 3, 2],
    "locked_top": [2, 1, 2, 1],
    "free": [2, 1, 2, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 12,
    "max_keys": 15,
    "progress": 13,
    "potential_progress": 14,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc54",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 1, 1, 0],
    "locked_top": [0, 1, 1, 2],
    "free": [2, 0, 1, 1],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 7,
    "max_keys": 12,
    "progress": 10,
    "potential_progress": 10,
    "unlocked_part": 1,
    "unlocked_empty": 0
  },
  {
    "name": "tc55",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [1, 2, 3, 1],
    "locked_top": [2, 1, 1, 1],
    "free": [4, 0, 1, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 12,
    "max_keys": 15,
    "progress": 14,
    "potential_progress": 14,
    "unlocked_part": 0,
    "unlocked_empty": 1
  },
  {
    "name": "tc56",
    "tctype": TestCaseType.FULL,
    "locked_bottom": [2, 2, 2, 1],
    "locked_top": [3, 1, 0, 1],
    "free": [5, 0, 2, 0],
    "free_bottom": [0, 0, 0, 0],
    "free_top": [0, 0, 0, 0],
    "free_full": [0, 0, 0, 0],
    "keys": 12,
    "max_keys": 15,
    "progress": 14,
    "potential_progress": 14,
    "unlocked_part": 0,
    "unlocked_empty": 0
  }
]
